
Vagrant.configure("2") do |config|

    config.vm.box = "ubuntu/trusty64"

    config.vm.network :private_network, ip: "192.168.33.11"

    config.vm.synced_folder "sites/", "/var/www/"

    config.vm.provider "virtualbox" do |vb|
      vb.gui = false
      vb.memory = "512"
    end

    config.ssh.insert_key = false

    config.vm.provision :shell, path: "Vagrant.bootstrap.sh"

end
