# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|

  config.vm.box = "ubuntu/trusty64"

  config.vm.network "private_network", ip: "192.168.100.100"

  if Vagrant::Util::Platform.windows?
      config.vm.synced_folder  "./www", "/var/www/",
      type: "nfs"
  else
      config.vm.synced_folder  "./www", "/var/www/",
      owner: "www-data", group: "root"
  end

  config.vm.provider "virtualbox" do |vb|
    vb.memory = "1024"
    vb.cpus = 1
  end

  config.ssh.insert_key = false

  config.vm.provision :shell, keep_color: true, path: "Vagrant.provision.sh"

end